### ISSUE TITLE
Month Dropdown issue

### ISSUE THREAD

**Issue by xytraguptor** [dangrossman/daterangepicker#1586]
This issue can be reproduced with the configuration generator.

With "showDropdowns" active, when selecting a month prior to the default one in the left dropdown, the options from the right one does not update accordingly and remain disabled.

All that that is needed is to call the correct update method (updateView/updateCalendars/updateFormInputs) in monthOrYearChanged, setStart/EndDate methods.

**Comment by TroyerPro** [comment]
Any way to solve it?

**Comment by xytraguptor** [comment]
not without modifying the library itself

**Comment by fr0z3nfyr** [comment]
I don't face this issue at least with `v2.1.25`. However, there is another major UX issue that let's say I first select `start` and `end` both dates and before applying, focus on end date input again and change the month. Now any date I select will update the `start` field instead of the expected `end` field (since it was explicitly focused) and expect a new `end` date which is completely wrong. The original `start` date should be retained while new selection must happen for `end` date. In short, it should respect the focus `start`/`end` fields if month/year is clicked.
