### ISSUE TITLE
I want its UI to be such that whenever i select the startdate it should get fixed, Same should be the case with end date. Righnow, It onlys shows the adjacent months in both the cases.

### ISSUE THREAD

**Issue by rish-rocks** [dangrossman/daterangepicker#1630]

**Comment by rish-rocks** [comment]
I want its UI to be such that whenever i select the startdate it should get fixed, Same should be the case with end date. Right now, It only shows the adjacent months in both the cases.

**Comment by dangrossman** [comment]
I don't understand your request.

**Comment by Othella** [comment]
@dangrossman For example if I choose January 1st. 2017 as start date and March 31. 2017 as end date, the UI shows January as start month and February as end month instead of March. It would be greater to have selected end month shown (actually it confuses users, they think they can only select a 2 months time range!). Thanks

**Comment by dangrossman** [comment]
Set `linkedCalendars: false` in your options
