### ISSUE TITLE
v3.0.2 includes a breaking change

### ISSUE THREAD

**Issue by roypeled** [dangrossman/daterangepicker#1742]
This commit: https://github.com/dangrossman/daterangepicker/commit/3afe364045e5aad8633c8e2fc40bc9628526a354
Is breaking all builds that upgrade from 3.0.1 to 3.0.2 and import the scss file.
It is not documented in the change log, and breaking changes should be released at least on a minor version, not a patch version.

**Comment by dangrossman** [comment]
The new CSS came with V3.0, while I forgot to delete the no-longer-matching-at-all SCSS file

**Comment by pmarreck** [comment]
Ran into this issue while updating a 2 year old codebase. Broke the asset compilation portion of my build because Sass for some reason couldn't resolve this @import directive in my app.scss, despite the .css file being RIGHT THERE: `@import '../node_modules/bootstrap-daterangepicker/daterangepicker';` But it DOES work when the .scss file is there.

Guess I have to downgrade to the last 2.x version :/

How are people including other css files from modules installed via node/npm, in their asset pipelines, these days? I may be a little out of date.

**Comment by pmarreck** [comment]
Also, FWIW, this is my only JS/CSS dependency that does not use a "dist" directory in its path to help indicate which .css/.scss file to include via globbing in asset management pipeline build tools
