### ISSUE TITLE
Support for monthly range picker

### ISSUE THREAD

**Issue by angelom88** [dangrossman/daterangepicker#1759]
It would be more nicer to add monthly picker for monthly range types.

**Comment by dangrossman** [comment]
Why not just use a `<select>` with the months listed?

**Comment by alexandrezap** [comment]
@dangrossman your datepicker is very good, has several features and settings but really misses a month picker, using a <select> does not solve because we have to validate date range, change the year according to the month, etc and all this is already done in your script, I think it would be very easy to implement this functionality
