### ISSUE TITLE
How to set only start date in daterange?

### ISSUE THREAD

**Issue by Kirigetov** [dangrossman/daterangepicker#1791]
How can I set the start date to a constant? To even after initialization, it was always equal to the current day. And a user could choose only the end date.

something like this
![deadline](https://user-images.githubusercontent.com/14583720/42370963-cc5ed140-8116-11e8-98ea-c69b163ceec6.png)

**Comment by dangrossman** [comment]
There is not an option for that, so your choices are:

* Find a different library that works like that

* Use a single date picker instead of a date range picker, since the user is only making a single selection

* Write your own thing

* Take the free open source code here as a starting point, and add to it to meet your requirements

**Comment by Kirigetov** [comment]
Thank you so much. I found a way out how to do my task using your plugin
