### ISSUE TITLE
Input Initially Empty Doesn't Work On Single Date Picker

### ISSUE THREAD

**Issue by chrisecmoffat** [dangrossman/daterangepicker#1793]
Initially on page load, the input box does not stay empty when the singleDatePicker attribute is added. It will work and stay empty until date is selected when the attribute singleDatePicker: false.

```
$scope.opts = {
     autoUpdateInput: false,
     singleDatePicker: true,
}
```

**Comment by dangrossman** [comment]
Are you using a different version of the library? Are your options not making it to the `daterangepicker()` function? Because there's no such problem. 

You can go ahead and try it out on the documentation site:

http://www.daterangepicker.com/#example5

Put in your console:

`$('input[name="datefilter"]').daterangepicker({ autoUpdateInput: false, singleDatePicker: true });`
