### ISSUE TITLE
Any way of making the whole daterangepicker work in UTC mode

### ISSUE THREAD

**Issue by shoobham** [dangrossman/daterangepicker#1827]
Our application totally works on UTC perspective of time. User selects the time according to UTC time and we show the ranges in UTC only.
Is there any way I can make the daterangepicker work according to UTC timezone no matter what timezone is set on the client's machine?

**Comment by dangrossman** [comment]
Sure, I have an application like that, and it's easy: just treat the output of the daterangepicker as a string. Construct all the date objects from that string in UTC time on your server. E.g. the user is picking "August 29 5PM" on the picker, you don't need to know what time zone is set on the client's machine, since you can take "August 29 5PM" and make an "August 29 5PM UTC" date object.

**Comment by nicolas-f** [comment]
Something like this is working:
```javascript
     $('input[name="datetimes"]').daterangepicker({
          "singleDatePicker": false,
          "showISOWeekNumbers": true,
          "maxSpan": {
               "month": 1
          },
          "timePicker": false,
          "autoApply": true,
          ranges: {
              'This Month': [moment().startOf('month'), moment().endOf('month')],
              'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
          },
          "startDate": moment().startOf('month'),
          "endDate": moment().endOf('month')
      }, function(start, end, label) {
        var startUTC = moment.utc(start.toString()).valueOf();
        var endUTC = moment.utc(end.toString()).valueOf();
      });
```
