### ISSUE TITLE
In report in date filter, currently, on click of the options like Today, yesterday, etc, the filter gets applied.   We need to give an extra step of "Apply" in that case as well. So if Last 30 days is selected, then the user will click on Apply and only then it will apply the filter.

### ISSUE THREAD

**Issue by aminsmartsense** [dangrossman/daterangepicker#1897]

**Comment by aminsmartsense** [comment]
In report in date filter, currently, on click of the options like Today, yesterday, etc, the filter gets applied. 

We need to give an extra step of "Apply" in that case as well. So if Last 30 days is selected, then the user will click on Apply and only then it will apply the filter.

**Comment by dangrossman** [comment]
You probably want to remove this line of code from your copy: 

https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L1180

**Comment by aminsmartsense** [comment]
@dangrossman I am using in Angular app, and that is installed in node_modules. I can not change it.

**Comment by dangrossman** [comment]
You are in full control of the code on your website. You can change whatever files you want. You can put your modified daterangepicker.js in your own repository with your other website files. You can fork it into its own repository and put that in your dependency list so that it gets installed in your node_modules. Either way, it does not require that I change this repository to contain code specifically for your website, whatever that is.

**Comment by aminsmartsense** [comment]
Yes, got your point. Thank for that. :)

But my question is if right now i am clicking on **"Last Month"** or **"This Month"** so that can be directly give filtered result in single click, but I need first select filter type after that on **"Apply"** button that filter can apply.
