### ISSUE TITLE
How set time default 

### ISSUE THREAD

**Issue by ameralrdadi** [dangrossman/daterangepicker#1926]
Hello 

I'm happy for use DateRangePicker 

How set time default now?  
* Because time Fixed "12:00"

`$('#reservation-time').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        timePicker: true,
        opens: 'center',
         locale: {
            format: 'MM/DD/YYYY h:s A',
        }`

Q2: How fix show message (Invalid date) 

`<input type="text"  id="reservation-time"  value="<?=date('Y/m/d h:i A', time())?>"  />`

Thanks

**Comment by dangrossman** [comment]
The `startDate` and `endDate` options set the default selected date range. Your values for those options may be `Date` or `moment` objects that include the time you want to be selected.

You are getting an invalid date error because you have set a date format of `MM/DD/YYYY` then provided an input value in the format `Y/m/d`. When "2019/3/5" is parsed as "MM/DD/YYYY" it is not a valid date, as there is no month 20...
