### ISSUE TITLE
moment.js dependency

### ISSUE THREAD

**Issue by pavelloz** [dangrossman/daterangepicker#1945]
Hello,

Are there any plans of making moment.js optional/replacable?

Nowadays there are some other options out there that dont bloat the package so much.

From momentjs authors - https://moment.github.io/luxon/
Date fns - much ligther - https://date-fns.org/

**Comment by dangrossman** [comment]
No. Also moment.min.js is smaller than luxon.min.js and date-fns.min.js.

**Comment by pavelloz** [comment]
Nope. Its bigger. 10x bigger than date-fns to be exact.

https://bundlephobia.com/result?p=moment@2.24.0 - 66KB
https://bundlephobia.com/result?p=luxon@1.12.1 - 18KB
https://bundlephobia.com/result?p=date-fns - 6.5KB

**Comment by pavelloz** [comment]
Heres $.02 about performance of it: https://dzone.com/articles/momentjs-vs-date-fns-how-to-spot-slow-loading-scri

**Comment by dangrossman** [comment]
![ss](https://user-images.githubusercontent.com/407706/56919819-8f62df80-6a8f-11e9-86e7-62c2cc1e56a7.png)

Not that it matters. I don't really want to make any breaking changes to this library. It's 7 years old. It's basically in maintenance mode.

**Comment by pavelloz** [comment]
Ouh, okay :)

**Comment by alvarotrigo** [comment]
But is moment really required?

I would also like to see it as an optional dependency. It is HUGE.

**Comment by Tropicalista** [comment]
I think that dayjs is good candidate

**Comment by stephanvierkant** [comment]
Would a PR to replace moment by dayjs be accepted?

**Comment by dangrossman** [comment]
no

**Comment by pavelloz** [comment]
@stephanvierkant can you fork and share your work with the world?

Im pretty sure in 2019 nobody should be using moment ;)

**Comment by stephanvierkant** [comment]
To be honest, I'm in doubt. I'm willing to give it a try, but since this library is in maintenance mode, I'm not sure if I want to spend time on this. I don't want to be responsible (on my own) for a fork of this library, since I'm not a JS expert.

I already spend some time in replacing moment by dayjs, but there are some notable differences. So it's not an easy 'find and replace' job, and that's why I doubt if that time is well spent. Maybe we should look at a more modern alternative like https://github.com/wakirin/lightpick (which has no jQuery dependency). See https://github.com/wakirin/Lightpick/issues/55

**Comment by pavelloz** [comment]
Sure thing, thanks for suggestion :)
