### ISSUE TITLE
Option to force only select one side option

### ISSUE THREAD

**Issue by aline-matos** [dangrossman/daterangepicker#1958]
Hi, how can I configure the plugin to have this behavior?

![daterangepicker](https://user-images.githubusercontent.com/5360477/57880201-8ba3bc80-77f4-11e9-8977-d0ee117d7b61.gif)

I mean, only allow to select start date on the left box and end date on the right box?

Thanks in advance!

**Comment by dangrossman** [comment]
There is not an option for that. Your video is of the first version of this plugin from 2012 which you can download here: https://github.com/dangrossman/daterangepicker/tree/v1.3.23

As I could not locate any date picker in the wild that worked like that on any hotel, airline, analytics, booking, etc website, the behavior was changed to match what people are used to, which is that the order of clicks determines what you're selecting rather than which calendar you click.
