### ISSUE TITLE
similar start and end dates, some way to reduce input text

### ISSUE THREAD

**Issue by muleroD** [dangrossman/daterangepicker#1980]
Hi, anyone know a way to display only a date when the values are the same. something similar to the single date picker but still using the range.

This image example I reduce the width using CSS

There is something like this, when the dates (start / end) are the same, the value of the input is only one value and when the range is displayed both

![image](https://user-images.githubusercontent.com/36611391/60840931-f6df8e80-a1a6-11e9-924d-d0a1ca9bf322.png)

**Comment by dangrossman** [comment]
Set `autoUpdateInput: false` in your options so that the date range picker does not put anything in your input at all. In your callback function or event listener for the `apply.daterangepicker` event, check if the two dates provided to your function are the same, and print what you want printed in your input accordingly. 

Some example code that might be helpful: http://www.daterangepicker.com/#example1 http://www.daterangepicker.com/#example5
