### ISSUE TITLE
daterangepicker is not a function in laravel app

### ISSUE THREAD

**Issue by ioanandrei** [dangrossman/daterangepicker#2017]
I have a fresh laravel app and i'm trying to use this datepicker.

I have this in my <head> 

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
```

and in my js file i use this  `$('#dates').daterangepicker();`

I always get this error: "daterangepicker is not a function";

Can you help me please?
I really don't know what to do.

**Comment by dangrossman** [comment]
Either those tags are missing from the page you're sending to the browser (added to wrong file?), or they're not being loaded before you try to create the picker, or you're loading jQuery twice and the daterangepicker extension is not being added to the same `$` you're using at that point... whatever the issue is, it's not debuggable from what you shared and isn't a bug in the library.
