### ISSUE TITLE
Value not applied to input when selected

### ISSUE THREAD

**Issue by macmichael01** [dangrossman/daterangepicker#2035]
When using a single date picker and a value is selected from the calendar, the newer value is not applied to the input box. Only when autoUpdateInput is set will the value apply.  autoUpdateInput also auto applies an initial value to the input. Where in my case I want the placeholder value of mm/dd/yyyy to initially display. Did I uncover a bug or is there something incorrectly defined?

~~~javascript
$('input[name="date_range_after"]').daterangepicker({
  singleDatePicker: true,
  autoUpdateInput: false,
});
~~~

**Comment by dangrossman** [comment]
This is neither a bug or anything incorrectly defined. "autoUpdateInput: false" means "do not automatically update my input". The behavior you're seeing is the behavior you requested. Since you don't want the picker to populate your input for you, but you do want it populated after a date is chosen, you need to add some more code to do that when a date is chosen. A full example is on the documentation site here, called "Input Initially Empty":

http://www.daterangepicker.com/#example5

**Comment by macmichael01** [comment]
Awh ok. I tried that earlier and my event wasn't firing seems to be working now. So.. blaming cache invalidation!
