### ISSUE TITLE
locale: format converts Date into String type

### ISSUE THREAD

**Issue by parminderjit-s** [dangrossman/daterangepicker#2075]
Hi, 
I noticed if I  set a locale like this 
locale:{
format:"DD/MM/YYYY"
}
The date automatically converts to String type. However, if I do not set the locale then it remains in Date type. The reason why I am using locale is only because I intend to change the date format on view. By default it appears MM/DD/YYYY but I would like it to be like DD/MM/YYYY. Setting a locale solves the format issue, but I am not able to save it because my model requires Date type and the locale somehow converts it into String type. Without the locale, I am able to map it to my model.

**Comment by dangrossman** [comment]
A form input contains a string. Perhaps whatever "model" you're talking about expects it to be in MM/DD/YYYY format to automatically convert it to a date. You'll have to write your own code to turn the string into a date. I can't help with that. This is just a UI widget for populating a form input from a calendar instead of the user typing. The callback function and event listeners have access to date/moment objects if that helps.

**Comment by sunco007** [comment]
Maybe the **Simple Date Range Picker With a Callback** sample works for you

You can put the date in the format you want to save on a hidden input

Btw, I use that locale-format but when I open the date picker it not selects the default date
