### ISSUE TITLE
Wrong week for year 2021

### ISSUE THREAD

**Issue by disiri** [dangrossman/daterangepicker#2183]
Hi,

Today is already iso week 11 but there seems to be something wrong in here. In jan, week 52 and 53 shows on second week of january too.

![image](https://user-images.githubusercontent.com/8130617/111451174-0e577480-8709-11eb-9d64-c45cfef54aad.png)
![image](https://user-images.githubusercontent.com/8130617/111451221-1b746380-8709-11eb-8c78-e9f8c5114aca.png)

**Comment by disiri** [comment]
Here is how I've initialized the picker
![image](https://user-images.githubusercontent.com/8130617/111451415-5080b600-8709-11eb-8223-9be6ed5d9da0.png)

**Comment by dangrossman** [comment]
You requested ISO week numbers. ISO week numbers start on Monday. January 3rd, 2021 was in week 53 of 2020. Week 1 of 2021 started on January 4th.

**Comment by disiri** [comment]
As you can see from the screenshot attached, week 1 of January 2021 started on January 10th.

**Comment by dangrossman** [comment]
ISO week 1 of  2021 is January 4th to January 10th. It did not start on January 10th, but since ISO weeks start on Mondays, a calendar that puts Sundays next to ISO week numbers will look/be wrong. As I said, either change the start day of your weeks to Mondays or use localized week numbers (showWeekNumbers) instead of ISO week numbers.

http://myweb.ecu.edu/mccartyr/isowdcal.html
